[package]
name = "auto-boot"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winres = "0.1.12"

[build-dependencies]
winres = "0.1.12"